name: Deploy Backend

on:
  push:
    branches:
      - main   # change if you use master or another branch

jobs:
  deploy:
    runs-on: self-hosted   # our EC2 runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm i --force

      - name: Restart backend with PM2
        run: |
          pm2 stop paragliding-backend || true
          pm2 start server.js --name paragliding-backend
          pm2 save
